# Task 1: Data Immersion & Wrangling
**Intership:** ApexPlaent Data Analytics Internship
**Task:** Task 1 - Data Immersion & Wragling
**Objective:**Understand, assess, clean, and prepare the dataset for analysis.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r"C:\Users\polaj\ApexPlanet-DataAnalytics-Internship\ApexPlanet_DataAnalytics_Dataset.xlsx")

In [3]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

## Dataset Overview

## Dataset Shape

In [4]:
df.shape

(1000, 12)

## Column Names

In [5]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age',
       'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price',
       'Total_Sales'],
      dtype='object')

## Dataset Information

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

## Summary Statistics

In [7]:
df.describe()

              Age     Quantity    Unit_Price    Total_Sales
count  980.000000  1000.000000   1000.000000    1000.000000
mean    41.360204     5.435000  25486.783410  139399.439650
std     13.822597     2.838632  14179.402361  114100.051546
min     18.000000     1.000000    145.780000     437.340000
25%     30.000000     3.000000  13895.722500   47066.632500
50%     41.000000     5.000000  25398.740000  108594.025000
75%     54.000000     8.000000  37512.382500  203722.882500
max     65.000000    10.000000  49997.530000  493677.500000

## Missing Values

In [8]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

## Duplicate Records

In [9]:
df.duplicated().sum()

np.int64(0)

# Data Cleaning

In [10]:
df_clean = df.copy()

In [11]:
df_clean.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [12]:
df_clean['Age'] = df_clean['Age'].fillna(df_clean['Age'].median())

In [13]:
df_clean['Age'].isnull().sum()

np.int64(0)

In [14]:
df_clean['City'] = df_clean['City'].fillna(df_clean['City'].mode()[0])

In [15]:
df_clean['City'].isnull().sum()

np.int64(0)

In [16]:
df_clean['Order_Date'] = pd.to_datetime(df_clean['Order_Date'])

In [17]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   datetime64[ns]
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            1000 non-null   float64
 5   Gender         1000 non-null   object
 6   City           1000 non-null   object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(7)
memory usage: 93.9+ KB

In [18]:
df_clean.duplicated().sum()

np.int64(0)

In [19]:
df_clean.isnull().sum()

Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Age              0
Gender           0
City             0
Product          0
Category         0
Quantity         0
Unit_Price       0
Total_Sales      0
dtype: int64

# Feature Engineering

In [20]:
df_clean['Order_Month'] = df_clean['Order_Date'].dt.month_name()

In [21]:
df_clean[['Order_Date', 'Order_Month']].head()

  Order_Date Order_Month
0 2025-02-25    February
1 2025-10-14     October
2 2025-05-13         May
3 2025-12-02    December
4 2025-11-20    November

In [25]:
df_clean['Order_Year'] = df_clean['Order_Date'].dt.year

In [26]:
df_clean[['Order_Date', 'Order_Year']].head()

  Order_Date  Order_Year
0 2025-02-25        2025
1 2025-10-14        2025
2 2025-05-13        2025
3 2025-12-02        2025
4 2025-11-20        2025

In [27]:
df_clean["Order_Quarter"] = "Q" + df_clean["Order_Date"].dt.quarter.astype(str)

In [28]:
df_clean[["Order_Date", "Order_Quarter"]].head()

  Order_Date Order_Quarter
0 2025-02-25            Q1
1 2025-10-14            Q4
2 2025-05-13            Q2
3 2025-12-02            Q4
4 2025-11-20            Q4

In [29]:
(df_clean["Quantity"] * df_clean["Unit_Price"]).head()

0     19808.39
1    139530.80
2    299928.48
3    256872.24
4    140365.90
dtype: float64

In [30]:
df_clean["Total_Sales"].head()

0     19808.39
1    139530.80
2    299928.48
3    256872.24
4    140365.90
Name: Total_Sales, dtype: float64

In [31]:
df_clean.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,Order_Month,Order_Year,Order_Quarter
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39,February,2025,Q1
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80,October,2025,Q4
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48,May,2025,Q2
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24,December,2025,Q4
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90,November,2025,Q4

In [32]:
df_clean.shape

(1000, 15)

In [33]:
df_clean.to_excel("ApexPlanet_DataAnalytics_Cleaned.xlsx", index=False)